### ISSUE TITLE
Problema com unwrapped quando não acha o modelo do meu Device.

### ISSUE THREAD

**Issue by nando0208** [payu-br/fcontrol-ios-fingerprint-framework#1]
O problema aconteceu quando precisei usar o método `retrieveDeviceModel` que retorna uma String!.
Esse método deu crash pois ele colocou no return o método `hardwareDescription` que retorna uma String?(Pode ser uma String ou um valor nil).

Toda vez que o método `hardwareDescription` não encontrar um device ele retornará um valor nil assim crashando o aplicativo. Não posso usar o framework com esse erro pois ele vai crashar o meu aplicativo assim que abrir ele com um device não citado na lista. No meu caso compilei o app com o Device `iPod touch (5th generation)`.

Vou propor algumas soluções de melhoria para o framework de vocês.
A primeira é usar esse Pod para pegar o ModelHardware do Device. UIDeviceHardware -> https://github.com/froztbytes/UIDeviceHardware.git. 

Outra melhoria(muito importante) é tratar todos os unwrapped de vocês. Esse artigo simples dá uma ideia das soluções que devem ser tomadas. 
http://krakendev.io/blog/when-to-use-implicitly-unwrapped-optionals

Aguardo um retorno.

**Comment by andersonkmi** [comment]
Caro @nando0208, 

obrigado pelas propostas, vamos análisá-las e proceder com as correções.

Atenciosamente.

Anderson.

**Comment by andersonkmi** [comment]
Iniciando testes.

**Comment by andersonkmi** [comment]
Corrigimos o tratamento dos optionals para evitar o retorno de nil e evitar o crash da aplicação. Com relação ao pod sugerido, vamos colocar na próxima versão.
